//
//  AboutView.m
//  NoiseMeter
//
//  Created by Dave Finster on 20/03/12.
//  Copyright (c) 2012 Internetics Pty Ltd. All rights reserved.
//

#import "AboutView.h"

@interface AboutView ()

@end

@implementation AboutView


- (void)loadView
{
    [super loadView];
    
    [self style];
    
    _textView = [[UITextView alloc] initWithFrame:CGRectMake(10, 105, self.view.frame.size.width - 20, self.view.frame.size.height - 105)];
    _textView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    _textView.text = @"\"Keep The Noise Down\" is fun way to measure and control the noise levels in your home, workplace, classroom, or anywhere you need to \"keep the noise down\". When the noise level generated by someone goes over your set limit an alarm is sounded and the name of that person can be recorded in the app.\n\nSet the your alarm trigger limit by by clicking \"Alert\". Typical settings might be 94 in a car, 90 in the house and so on. Experiment with the settings depending on how far away from the device your subjects are, and your environment.\n\nWhen someone goes over the limit, name and shame them by clicking \"Capture\", and record their name in the list of top noise makers.\n\nPlease note that the decibel limits shown are for an approximate guidance only, are not scientifically tested or calculated and should not be relied upon for accuracy. Readings will vary from device to device and environment to environment.\n\nKeep the Noise Down is an app developed by Internetics.";
    _textView.backgroundColor = [UIColor blackColor];
    _textView.textColor = [UIColor whiteColor];
    _textView.editable = NO;
    [self.view addSubview:_textView];
}

- (void)viewDidUnload
{
    [super viewDidUnload];
    _textView = nil;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
{
    return (interfaceOrientation == UIInterfaceOrientationPortrait);
}

@end
