//
//  MeterView.m
//  NoiseMeter
//
//  Created by Dave Finster on 6/03/12.
//  Copyright (c) 2012 Internetics Pty Ltd. All rights reserved.
//

#import "MeterView.h"
#import "NMDecibelLogger.h"
#import "CaptureView.h"
#import "SoundLevelCapture.h"
#import "SoundLevelCaptureCell.h"
#import "PurchaseViewController.h"
#import "FileHelper.h"
#import "PlayHelper.h"

@interface MeterView ()

@end

@implementation MeterView

- (id)init
{
    self = [super init];
    self.title = @"Meter";
    self.tabBarItem.image = [UIImage imageNamed:@"icon_meter.png"];
    
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(alarmFinishedNotification:)
                                                 name:@"ALARM_FINISHED_NOTIFICATION"
                                               object:nil];
    
    
    
    return self;
}

- (void)failed
{
    _currentReadingLabel.text = @"N/A";
    [_soundLevelView setSoundLevelValue:0];
    _currentReadingLabel.textColor = [UIColor redColor];
    
    _cancelButton.hidden = NO;
    CGRect rect = _currentReadingLabel.frame;
    rect.origin.x = 50;
    _currentReadingLabel.frame = rect;
}

- (void)reloadData
{
    _scores = [SoundLevelCapture all];
    NSSortDescriptor *desc = [NSSortDescriptor sortDescriptorWithKey:@"soundLevel" ascending:NO];
    _scores = [_scores sortedArrayUsingDescriptors:[NSArray arrayWithObject:desc]];
    _titleLabel.numberOfLines = 3;
    if ([_scores count] == 0) 
    {
        _titleLabel.text = @"  Top Noise Makers:\n\n  None recorded";
    }
    else 
    {
        _titleLabel.text = @"  Top Noise Makers:\n\n";
    }
    [_topScoreTable reloadData];
}

- (void) cancel {
    
    [[NMDecibelLogger defaultLogger] alarmComplete];
    
}

- (void)infoShow
{
    [self displayHelpOverlayWithText:@"\"Keep The Noise Down\" is fun way to measure and control the noise levels in your home, workplace, classroom, or anywhere you need to \"keep the noise down\". When the noise level generated by someone goes over your set limit an alarm is sounded and the name of that person can be recorded in the app.\n\nSet the your alarm trigger limit by by clicking \"Alert\". Typical settings might be 94 in a car, 90 in the house and so on. Experiment with the settings depending on how far away from the device your subjects are, and your environment.\n\nWhen someone goes over the limit, name and shame them by clicking \"Capture\", and record their name in the list of top noise makers."];
}

- (void)loadView
{
    [super loadView];
    
    [self style];
    
    _meterBackground = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"background_count.png"]];
    _meterBackground.frame = CGRectMake(0, 79, 320, 150);
    _meterBackground.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleBottomMargin;
    _meterBackground.userInteractionEnabled = YES;
    [self.view addSubview:_meterBackground];
    UITapGestureRecognizer *singleTapGesture = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(switchLoggingStatus)];
    singleTapGesture.numberOfTapsRequired = 1;
    singleTapGesture.numberOfTouchesRequired = 1;
    [_meterBackground addGestureRecognizer:singleTapGesture];
    
    _infoButton = [UIButton buttonWithType:UIButtonTypeCustom];
    [_infoButton setImage:[UIImage imageNamed:@"button_info.png"] forState:UIControlStateNormal];
    _infoButton.frame = CGRectMake(self.view.frame.size.width - 30, _meterBackground.frame.origin.y, 30, 30);
    [_infoButton addTarget:self action:@selector(infoShow) forControlEvents:UIControlEventTouchUpInside];
    [self.view addSubview:_infoButton];
    
    _cancelButton = [UIButton buttonWithType:UIButtonTypeCustom];
    [_cancelButton setImage:[UIImage imageNamed:@"cancel.png"] forState:UIControlStateNormal];
    _cancelButton.frame = CGRectMake(10, _meterBackground.frame.origin.y + 10, 30, 30);
    [_cancelButton addTarget:self action:@selector(cancel) forControlEvents:UIControlEventTouchUpInside];
    _cancelButton.hidden = YES;
    [self.view addSubview:_cancelButton];
    
    _currentReadingLabel = [[UILabel alloc] initWithFrame:
                            CGRectMake(10, _meterBackground.frame.origin.y + 5, 150, 40)];
    _currentReadingLabel.textAlignment = UITextAlignmentLeft;
    _currentReadingLabel.font = [UIFont fontWithName:@"Helvetica-Bold" size:40];
    _currentReadingLabel.textColor = [UIColor greenColor];
    _currentReadingLabel.backgroundColor = [UIColor clearColor];
    _currentReadingLabel.userInteractionEnabled = YES;
    [self.view addSubview:_currentReadingLabel];
    
    _soundLevelView = [[SoundLevelView alloc] initWithFrame:CGRectMake(10, _meterBackground.frame.origin.y + 40, 310, _meterBackground.frame.size.height -65)];
    [_soundLevelView setupSubviews];
    _soundLevelView.backgroundColor = [UIColor clearColor];
    [self.view addSubview:_soundLevelView];
    [_soundLevelView addGestureRecognizer:singleTapGesture];
    
    [[NMDecibelLogger defaultLogger] addObserver:self forKeyPath:@"currentReading" options:NSKeyValueObservingOptionNew context:NULL];
    [[NMDecibelLogger defaultLogger] startLogging];
    
    _captureButton = [UIButton buttonWithType:UIButtonTypeCustom];
    [_captureButton setImage:[UIImage imageNamed:@"button_capture.png"] forState:UIControlStateNormal];
    _captureButton.frame = CGRectMake(self.view.frame.size.width - 89, _meterBackground.frame.origin.y + _meterBackground.frame.size.height - 20, 89, 29);
    [self.view addSubview:_captureButton];
    _captureButton.hidden = YES;
    [_captureButton addTarget:self action:@selector(capture) forControlEvents:UIControlEventTouchUpInside];
    
    _peakLabel = [[UILabel alloc] initWithFrame:CGRectMake(10, _captureButton.frame.origin.y, 200, 29)];
    _peakLabel.textColor = [UIColor whiteColor];
    _peakLabel.backgroundColor = [UIColor clearColor];
    [self.view addSubview:_peakLabel];
    _peakLabel.hidden = YES;
    
    [self reloadData];
    
    _formBackground = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"background_count.png"]];
    _formBackground.frame = CGRectMake(0, _meterBackground.frame.origin.y + _meterBackground.frame.size.height + 10, 320, 150);
    _formBackground.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleBottomMargin;
    [self.view addSubview:_formBackground];
    
    _topScoreTable = [[UITableView alloc] initWithFrame:CGRectMake(0, _captureButton.frame.origin.y + _captureButton.frame.size.height, self.view.frame.size.width, self.view.frame.size.height - (_meterBackground.frame.origin.y + _meterBackground.frame.size.height)) style:UITableViewStylePlain];
    _topScoreTable.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    _topScoreTable.backgroundView = nil;
    _topScoreTable.separatorColor = [UIColor colorWithRed:0.152 green:0.156 blue:0.164 alpha:1.0];
    _topScoreTable.backgroundColor = [UIColor clearColor];
    _topScoreTable.opaque = YES;
    _topScoreTable.delegate = self;
    _topScoreTable.scrollEnabled = NO;
    _topScoreTable.dataSource = self;
    [self.view addSubview:_topScoreTable];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(reloadData) name:@"SoundCaptured" object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(failed) name:@"RecordFail" object:nil];
    
    BOOL flag = [NSUserDefaultsHelper isAdRemoved];
    if (flag == FALSE) {
        if (isUseGoogleAdmob) {
            //we don't need ADMOB function again, keep here for future use
//            _bannerView = [[DFPBannerView alloc] initWithAdSize:kGADAdSizeBanner];
//            _bannerView.adUnitID = @"a152e9fa5524978";
//            _bannerView.delegate = self;
//            _bannerView.rootViewController = self;
//            [self.view addSubview:_bannerView];
//            [_bannerView loadRequest:[GADRequest request]];
            
            
        } else {
            CGRect rect = CGRectMake(0, self.view.bounds.size.height - 50 - 49, self.view.bounds.size.width, 50);
            adView = [[ADBannerView alloc] initWithFrame:rect];
            adView.backgroundColor = [UIColor darkGrayColor];
            adView.delegate = self;
            [self.view addSubview:adView];
            
            removeADButton = [UIButton buttonWithType:UIButtonTypeCustom];
            removeADButton.frame = CGRectMake(self.view.bounds.size.width - 24 +2, self.view.bounds.size.height - 49 - 50 - 24 +3, 24, 24);
            [removeADButton setImage:[UIImage imageNamed:@"remove_ad.png"] forState:UIControlStateNormal];
            [removeADButton addTarget:self action:@selector(goToPurchasePage) forControlEvents:UIControlEventTouchDown];
            removeADButton.showsTouchWhenHighlighted = TRUE;
            [self.view addSubview:removeADButton];
        }
    }
}

- (void) goToPurchasePage {
    PurchaseViewController *purchaseViewController = [[PurchaseViewController alloc] initWithNibName:@"PurchaseViewController" bundle:nil];
    [self.navigationController pushViewController:purchaseViewController animated:YES];
}

- (void)viewDidLoad {
    [super viewDidLoad];
}


- (void)capture
{
    CaptureView *cap = [[CaptureView alloc] initWithReading:_peakReading];
    [self.navigationController pushViewController:cap animated:YES];
}

- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section
{
    if (_headerView == nil) 
    {
        _headerView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, self.view.frame.size.width, 66)];
        _titleLabel = [[UILabel alloc] initWithFrame:CGRectMake(5, 10, _headerView.frame.size.width - 10, _headerView.frame.size.height)];
        _titleLabel.backgroundColor = [UIColor clearColor];
        _titleLabel.numberOfLines = 3;
        if ([_scores count] == 0) 
        {
            _titleLabel.text = @"  Top Noise Makers:\n\n  None recorded";
        }
        else 
        {
            _titleLabel.text = @"  Top Noise Makers:\n\n";
        }
        _titleLabel.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
        _titleLabel.font = [UIFont fontWithName:@"Helvetica-Bold" size:_titleLabel.font.pointSize];
        _titleLabel.textColor = [UIColor whiteColor];
        [_headerView addSubview:_titleLabel];
    }
    return _headerView;
}

- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section
{
    if ([_scores count] == 0) 
    {
        return 66;
    }
    else 
    {
        return 50;
    }
}

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath
{
    return 44;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return [_scores count];
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    SoundLevelCaptureCell *cell = (SoundLevelCaptureCell *)[tableView dequeueReusableCellWithIdentifier:@"Sound"];
    if (cell == nil) {
        cell = [[SoundLevelCaptureCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"Sound"];
        cell.selectionStyle = UITableViewCellSelectionStyleNone;
        cell.textLabel.textColor = [UIColor whiteColor];
    }
    cell.capture = [_scores objectAtIndex:indexPath.row];
    cell.backgroundColor = [UIColor clearColor];
    
    cell.playButton.tag = indexPath.row;
    [cell.playButton addTarget:self action:@selector(playRecordedSound:) forControlEvents:UIControlEventTouchDown];
    
    BOOL flag = [NSUserDefaultsHelper isAdRemoved];
    if (flag) {
        cell.playButton.hidden = NO;
    } else {
        cell.playButton.hidden = YES;
    }
    
    return cell;
}


- (void) playRecordedSound: (id) sender {
    
    if ([[NMDecibelLogger defaultLogger] logging]) {
        [[NMDecibelLogger defaultLogger] stopLogging];
    }
    
    dispatch_async(dispatch_get_main_queue(), ^{
        _currentReadingLabel.text = @"Playing";
    });
    
    int index = ((UIButton *) sender).tag;
    
    SoundLevelCapture *caputure = [_scores objectAtIndex:index];
    
    NSDate *date = caputure.date;
	NSString *dateString = [FileHelper convertDate:date];
    
    NSURL *url = [FileHelper getRecordedAudioFile:dateString];
    
    [PlayHelper playAudioFile:url];
}

- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context
{
    if ([keyPath isEqualToString:@"currentReading"]) 
    {
        _currentReading = [[NMDecibelLogger defaultLogger] currentReading];
        _currentReadingLabel.text = [NSString stringWithFormat:@"%.1f", [_currentReading floatValue]];
        [_soundLevelView setSoundLevelValue:[_currentReading floatValue]];
        NSNumber *threshold = [NMDecibelLogger defaultLogger].alertThreshold;
        if ((_peakReading == nil) || ([_peakReading floatValue] < [_currentReading floatValue])) 
        {
            _peakReading = _currentReading;
            
        }
        if ((threshold != nil) && ([threshold floatValue] < [_currentReading floatValue])) 
        {
            _currentReadingLabel.textColor = [UIColor redColor];
            [[NMDecibelLogger defaultLogger] playAlarm];
        }
        else 
        {
            _currentReadingLabel.textColor = [UIColor greenColor];
        }
        if ((threshold != nil) && ([threshold floatValue] < [_currentReading floatValue])) 
        {
            _peakLabel.hidden = NO;
            _peakLabel.text = [NSString stringWithFormat:@"Last Peak: %.1f", [_peakReading floatValue]];
            _captureButton.hidden = NO;
            _cancelButton.hidden = NO;
            CGRect rect = _currentReadingLabel.frame;
            rect.origin.x = 50;
            _currentReadingLabel.frame = rect;
        }
    }
    else 
    {
        [super observeValueForKeyPath:keyPath ofObject:object change:change context:context];
    }
}

- (void)viewDidDisappear:(BOOL)animated
{
    _peakReading = nil;
    //_captureButton.hidden = YES;
    _peakLabel.hidden = YES;
    [super viewDidDisappear:animated];
}

- (void) viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    self.trackedViewName = @"MeterView Screen";

}

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    _cancelButton.hidden = YES;
    _captureButton.hidden = YES;
    
    CGRect rect = _currentReadingLabel.frame;
    rect.origin.x = 10;
    _currentReadingLabel.frame = rect;
}


- (void)viewDidUnload
{
    [super viewDidUnload];
    
    _currentReadingLabel = nil;
    [_soundLevelView setSoundLevelValue:0];
    _meterBackground = nil;
    [[NMDecibelLogger defaultLogger] stopLogging];
    [[NSNotificationCenter defaultCenter] removeObserver:self name:@"SoundCaptured" object:nil];
    [[NSNotificationCenter defaultCenter] removeObserver:self name:@"RecordFail" object:nil];
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
{
    return (interfaceOrientation == UIInterfaceOrientationPortrait);
}

- (void)alarmFinishedNotification:(NSNotification *)notification {
    _captureButton.hidden = YES;
    _cancelButton.hidden = YES;
    
    CGRect rect = _currentReadingLabel.frame;
    rect.origin.x = 10;
    _currentReadingLabel.frame = rect;
}


- (void)purchasedFinishedNotification:(NSNotification *)notification {
    
    [super purchasedFinishedNotification:notification];
    
    [adView removeFromSuperview];
    [removeADButton removeFromSuperview];
    adView.hidden = TRUE;
    removeADButton.hidden = TRUE;
    
    //we don't need ADMOB function again, keep here for future use
//    [_bannerView removeFromSuperview];
//    _bannerView.hidden = TRUE;
    
    [NSUserDefaultsHelper setAdRemoveFlag:YES];
    
    [_topScoreTable reloadData];
}

- (void)dealloc
{
    [self viewDidUnload];
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}

- (void)bannerView:(ADBannerView *)banner didFailToReceiveAdWithError:(NSError *)error {
    NSLog(@"didFailToReceiveAdWithError, %@",[error description]);
}


#pragma mark GADBannerViewDelegate

- (void)adViewDidReceiveAd:(DFPBannerView *)adView {
    NSLog(@"Received ad successfully");
    
    //we don't need ADMOB function again, keep here for future use
//    if (SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"7.0")) {
//        _bannerView.center = CGPointMake(self.view.center.x,
//                                         CGRectGetHeight(self.view.frame) - 49 - CGRectGetHeight(_bannerView.frame)/2);
//    } else {
//        _bannerView.center = CGPointMake(self.view.center.x,
//                                         CGRectGetHeight(self.view.frame) - CGRectGetHeight(_bannerView.frame)/2);
//    }
}

- (void)adView:(DFPBannerView *)view
didFailToReceiveAdWithError:(GADRequestError *)error {
    NSLog(@"Failed to receive ad with error: %@", [error localizedFailureReason]);
}

#pragma mark – Others
- (void) switchLoggingStatus {
    
    if ([[NMDecibelLogger defaultLogger] logging]) {
        [[NMDecibelLogger defaultLogger] stopLogging];
        
        _currentReadingLabel.text = @"Pause";
        
        UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Alert" message:@"Paused. Tap again to resume." delegate:nil cancelButtonTitle:@"OK" otherButtonTitles:nil];
        [alert show];
        
    } else {
        [[NMDecibelLogger defaultLogger] startLogging];
    }
    
    
}


@end
