//
//  MeterView.m
//  NoiseMeter
//
//  Created by Dave Finster on 6/03/12.
//  Copyright (c) 2012 Internetics Pty Ltd. All rights reserved.
//

#import "MeterView.h"
#import "NMDecibelLogger.h"
#import "CaptureView.h"
#import "SoundLevelCapture.h"
#import "SoundLevelCaptureCell.h"

@interface MeterView ()

@end

@implementation MeterView

- (id)init
{
    self = [super init];
    self.title = @"Meter";
    self.tabBarItem.image = [UIImage imageNamed:@"icon_meter.png"];
    
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(alarmFinishedNotification:)
                                                 name:@"ALARM_FINISHED_NOTIFICATION"
                                               object:nil];
    
    return self;
}

- (void)failed
{
    _currentReadingLabel.text = @"N/A";
    _currentReadingLabel.textColor = [UIColor redColor];
}

- (void)reloadData
{
    _scores = [SoundLevelCapture all];
    NSSortDescriptor *desc = [NSSortDescriptor sortDescriptorWithKey:@"soundLevel" ascending:NO];
    _scores = [_scores sortedArrayUsingDescriptors:[NSArray arrayWithObject:desc]];
    _titleLabel.numberOfLines = 3;
    if ([_scores count] == 0) 
    {
        _titleLabel.text = @"  Top Noise Makers:\n\n  None recorded";
    }
    else 
    {
        _titleLabel.text = @"  Top Noise Makers:\n\n";
    }
    [_topScoreTable reloadData];
}

- (void)infoShow
{
    [self displayHelpOverlayWithText:@"\"Keep The Noise Down\" is fun way to measure and control the noise levels in your home, workplace, classroom, or anywhere you need to \"keep the noise down\". When the noise level generated by someone goes over your set limit an alarm is sounded and the name of that person can be recorded in the app.\n\nSet the your alarm trigger limit by by clicking \"Alert\". Typical settings might be 94 in a car, 90 in the house and so on. Experiment with the settings depending on how far away from the device your subjects are, and your environment.\n\nWhen someone goes over the limit, name and shame them by clicking \"Capture\", and record their name in the list of top noise makers."];
}

- (void)loadView
{
    [super loadView];
    
    [self style];
    
    _meterBackground = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"background_count.png"]];
    _meterBackground.frame = CGRectMake(0, 79, 320, 150);
    _meterBackground.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleBottomMargin;
    [self.view addSubview:_meterBackground];
    
    _infoButton = [UIButton buttonWithType:UIButtonTypeCustom];
    [_infoButton setImage:[UIImage imageNamed:@"button_info.png"] forState:UIControlStateNormal];
    _infoButton.frame = CGRectMake(self.view.frame.size.width - 30, _meterBackground.frame.origin.y, 30, 30);
    [_infoButton addTarget:self action:@selector(infoShow) forControlEvents:UIControlEventTouchUpInside];
    [self.view addSubview:_infoButton];
    
    _currentReadingLabel = [[UILabel alloc] initWithFrame:_meterBackground.frame];
    _currentReadingLabel.textAlignment = UITextAlignmentCenter;
    _currentReadingLabel.font = [UIFont fontWithName:@"Helvetica-Bold" size:90];
    _currentReadingLabel.center = _meterBackground.center;
    _currentReadingLabel.textColor = [UIColor greenColor];
    _currentReadingLabel.backgroundColor = [UIColor clearColor];
    [self.view addSubview:_currentReadingLabel];
    
    [[NMDecibelLogger defaultLogger] addObserver:self forKeyPath:@"currentReading" options:NSKeyValueObservingOptionNew context:NULL];
    [[NMDecibelLogger defaultLogger] startLogging];
    
    _captureButton = [UIButton buttonWithType:UIButtonTypeCustom];
    [_captureButton setImage:[UIImage imageNamed:@"button_capture.png"] forState:UIControlStateNormal];
    _captureButton.frame = CGRectMake(self.view.frame.size.width - 89, _meterBackground.frame.origin.y + _meterBackground.frame.size.height - 20, 89, 29);
    [self.view addSubview:_captureButton];
    _captureButton.hidden = YES;
    [_captureButton addTarget:self action:@selector(capture) forControlEvents:UIControlEventTouchUpInside];
    
    _peakLabel = [[UILabel alloc] initWithFrame:CGRectMake(0, _captureButton.frame.origin.y, 200, 29)];
    _peakLabel.textColor = [UIColor whiteColor];
    _peakLabel.backgroundColor = [UIColor clearColor];
    [self.view addSubview:_peakLabel];
    _peakLabel.hidden = YES;
    
    [self reloadData];
    
    _formBackground = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"background_count.png"]];
    _formBackground.frame = CGRectMake(0, _meterBackground.frame.origin.y + _meterBackground.frame.size.height + 10, 320, 150);
    _formBackground.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleBottomMargin;
    [self.view addSubview:_formBackground];
    
    _topScoreTable = [[UITableView alloc] initWithFrame:CGRectMake(0, _captureButton.frame.origin.y + _captureButton.frame.size.height, self.view.frame.size.width, self.view.frame.size.height - (_meterBackground.frame.origin.y + _meterBackground.frame.size.height)) style:UITableViewStylePlain];
    _topScoreTable.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    _topScoreTable.backgroundView = nil;
    _topScoreTable.separatorColor = [UIColor colorWithRed:0.152 green:0.156 blue:0.164 alpha:1.0];
    _topScoreTable.backgroundColor = [UIColor clearColor];
    _topScoreTable.opaque = YES;
    _topScoreTable.delegate = self;
    _topScoreTable.scrollEnabled = NO;
    _topScoreTable.dataSource = self;
    [self.view addSubview:_topScoreTable];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(reloadData) name:@"SoundCaptured" object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(failed) name:@"RecordFail" object:nil];
    
    NSUserDefaults *userDefaults = [NSUserDefaults standardUserDefaults];
    BOOL flag = [userDefaults boolForKey:@"AD_REMOVED"];
    
    if (flag == FALSE) {
        CGRect rect = CGRectMake(0, self.view.bounds.size.height - 50 - 44, self.view.bounds.size.width, 50);
        adView = [[ADBannerView alloc] initWithFrame:rect];
        adView.backgroundColor = [UIColor darkGrayColor];
        adView.delegate = self;
        [self.view addSubview:adView];
        
        removeADButton = [UIButton buttonWithType:UIButtonTypeCustom];
        removeADButton.frame = CGRectMake(self.view.bounds.size.width - 24 +2, self.view.bounds.size.height - 44 - 50 - 24 +3, 24, 24);
        [removeADButton setImage:[UIImage imageNamed:@"remove_ad.png"] forState:UIControlStateNormal];
        [removeADButton addTarget:self action:@selector(removeAD) forControlEvents:UIControlEventTouchDown];
        removeADButton.showsTouchWhenHighlighted = TRUE;
        [self.view addSubview:removeADButton];
        
    }
}

- (void)viewDidLoad {
    [super viewDidLoad];
    // Listen to purchase
    [[SKPaymentQueue defaultQueue] addTransactionObserver:self];
}

- (void) removeAD {
    
    if ([SKPaymentQueue canMakePayments]) {
        
        NSSet * set = [NSSet setWithArray:@[IAPProductID]];
        SKProductsRequest * request = [[SKProductsRequest alloc] initWithProductIdentifiers:set];
        request.delegate = self;
        [request start];
        
    } else {
        NSLog(@"Failure，forbid to allow for purchase");
    }
    
}


- (void)bannerView:(ADBannerView *)banner didFailToReceiveAdWithError:(NSError *)error {
    NSLog(@"didFailToReceiveAdWithError, %@",[error description]);
}

- (void)productsRequest:(SKProductsRequest *)request didReceiveResponse:(SKProductsResponse *)response {
    NSArray *myProduct = response.products;
    
    if (myProduct.count == 0) {
        NSLog(@"Fail to get purchase info (myProduct.count = 0)");
        return;
    }
    
    NSArray *invalidProductID = response.invalidProductIdentifiers;
    if ([invalidProductID count] >0) {
        NSLog(@"Invalid product ID");
        return;
    }
    
    skProduct = [myProduct lastObject];
    NSLog(@"Product title: %@" , skProduct.localizedTitle);
    NSLog(@"Product description: %@" , skProduct.localizedDescription);
    NSLog(@"Product price: %@" , skProduct.price);
    NSLog(@"Product id: %@" , skProduct.productIdentifier);
    
    UIAlertView *alertView = [[UIAlertView alloc] initWithTitle:@"Alert"
                                                        message:[NSString stringWithFormat:@"Confirm to buy (%@)?",[self localizedPrice:skProduct]]
                                                       delegate:self
                                              cancelButtonTitle:@"Cancel"
                                              otherButtonTitles:@"OK", nil];
    [alertView show];
}


- (void)alertView:(UIAlertView *)alertView clickedButtonAtIndex:(NSInteger)buttonIndex {
    if (buttonIndex == 1) {
        SKPayment * payment = [SKPayment paymentWithProduct:skProduct];
        [[SKPaymentQueue defaultQueue] addPayment:payment];
    }
}

- (NSString *)localizedPrice: (SKProduct *) sk
{
    NSNumberFormatter *numberFormatter = [[NSNumberFormatter alloc] init];
    [numberFormatter setFormatterBehavior:NSNumberFormatterBehavior10_4];
    [numberFormatter setNumberStyle:NSNumberFormatterCurrencyStyle];
    [numberFormatter setLocale:sk.priceLocale];
    NSString *formattedString = [numberFormatter stringFromNumber:sk.price];
    return formattedString;
}


- (void)paymentQueue:(SKPaymentQueue *)queue updatedTransactions:(NSArray *)transactions {
    UIAlertView *alertView;
    for (SKPaymentTransaction *transaction in transactions)
    {
        switch (transaction.transactionState)
        {
            case SKPaymentTransactionStatePurchased:
                NSLog(@"Done of purchase transactionIdentifier = %@", transaction.transactionIdentifier);
                [self purchaseDoneAfterAction];
                break;
            case SKPaymentTransactionStateFailed:
                /*
                alertView = [[UIAlertView alloc] initWithTitle:@"Alert"
                                                                    message:[NSString stringWithFormat:@"Failure to purchase, try again"]
                                                                   delegate:self
                                                          cancelButtonTitle:@"OK"
                                                          otherButtonTitles:nil, nil];
                [alertView show];*/
                NSLog(@"Fail to purchase");
                break;
            case SKPaymentTransactionStateRestored:
                NSLog(@"Fail to purchase: have bought this before");
                [self purchaseDoneAfterAction];
                break;
            case SKPaymentTransactionStatePurchasing:      //商品添加进列表
                NSLog(@"Add item into list to purchase");
                break;
            default:
                break;
        }
    }
    
}

- (void) purchaseDoneAfterAction {
    [adView removeFromSuperview];
    [removeADButton removeFromSuperview];
    
    NSUserDefaults *userDefaults = [NSUserDefaults standardUserDefaults];
    [userDefaults setBool:TRUE forKey:@"AD_REMOVED"];
    [userDefaults synchronize];
}

- (void)capture
{
    CaptureView *cap = [[CaptureView alloc] initWithReading:_peakReading];
    [self.navigationController pushViewController:cap animated:YES];
}

- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section
{
    if (_headerView == nil) 
    {
        _headerView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, self.view.frame.size.width, 66)];
        _titleLabel = [[UILabel alloc] initWithFrame:CGRectMake(5, 10, _headerView.frame.size.width - 10, _headerView.frame.size.height)];
        _titleLabel.backgroundColor = [UIColor clearColor];
        _titleLabel.numberOfLines = 3;
        if ([_scores count] == 0) 
        {
            _titleLabel.text = @"  Top Noise Makers:\n\n  None recorded";
        }
        else 
        {
            _titleLabel.text = @"  Top Noise Makers:\n\n";
        }
        _titleLabel.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
        _titleLabel.font = [UIFont fontWithName:@"Helvetica-Bold" size:_titleLabel.font.pointSize];
        _titleLabel.textColor = [UIColor whiteColor];
        [_headerView addSubview:_titleLabel];
    }
    return _headerView;
}

- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section
{
    if ([_scores count] == 0) 
    {
        return 66;
    }
    else 
    {
        return 50;
    }
}

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath
{
    return 44;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return [_scores count];
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    SoundLevelCaptureCell *cell = (SoundLevelCaptureCell *)[tableView dequeueReusableCellWithIdentifier:@"Sound"];
    if (cell == nil) {
        cell = [[SoundLevelCaptureCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"Sound"];
        cell.selectionStyle = UITableViewCellSelectionStyleNone;
        cell.textLabel.textColor = [UIColor whiteColor];
    }
    cell.capture = [_scores objectAtIndex:indexPath.row];
    
    return cell;
}

- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context
{
    if ([keyPath isEqualToString:@"currentReading"]) 
    {
        _currentReading = [[NMDecibelLogger defaultLogger] currentReading];
        _currentReadingLabel.text = [NSString stringWithFormat:@"%.1f", [_currentReading floatValue]];
        NSNumber *threshold = [NMDecibelLogger defaultLogger].alertThreshold;
        if ((_peakReading == nil) || ([_peakReading floatValue] < [_currentReading floatValue])) 
        {
            _peakReading = _currentReading;
            
        }
        if ((threshold != nil) && ([threshold floatValue] < [_currentReading floatValue])) 
        {
            _currentReadingLabel.textColor = [UIColor redColor];
            [[NMDecibelLogger defaultLogger] playAlarm];
        }
        else 
        {
            _currentReadingLabel.textColor = [UIColor greenColor];
        }
        if ((threshold != nil) && ([threshold floatValue] < [_currentReading floatValue])) 
        {
            _peakLabel.hidden = NO;
            _peakLabel.text = [NSString stringWithFormat:@"Last Peak: %.1f", [_peakReading floatValue]];
            _captureButton.hidden = NO;
        }
    }
    else 
    {
        [super observeValueForKeyPath:keyPath ofObject:object change:change context:context];
    }
}

- (void)viewDidDisappear:(BOOL)animated
{
    _peakReading = nil;
    //_captureButton.hidden = YES;
    _peakLabel.hidden = YES;
    [super viewDidDisappear:animated];
}

- (void) viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    self.trackedViewName = @"MeterView Screen";
}

- (void)viewDidUnload
{
    [super viewDidUnload];
    
    [[SKPaymentQueue defaultQueue] removeTransactionObserver:self];
    
    _currentReadingLabel = nil;
    _meterBackground = nil;
    [[NMDecibelLogger defaultLogger] stopLogging];
    [[NSNotificationCenter defaultCenter] removeObserver:self name:@"SoundCaptured" object:nil];
    [[NSNotificationCenter defaultCenter] removeObserver:self name:@"RecordFail" object:nil];
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
{
    return (interfaceOrientation == UIInterfaceOrientationPortrait);
}

- (void)alarmFinishedNotification:(NSNotification *)notification {
    _captureButton.hidden = YES;        
}

- (void)dealloc
{
    [self viewDidUnload];
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}

@end
